### PR TITLE
conda environment for 2021_2 APS run cycle

### LINKED ISSUE #101: environment for 2021-2 APS cycle
name: bluesky_2021_2

As part of the process, identify which package(s) make the `conda env create` process take so much longer to solve.

### PR DESCRIPTION
**Pull request by prjemian**
FIX #101

@gfabbris: Please test with this and review here on GitHub.

### CODE REVIEW

**Comment by prjemian** [comment]
In my [testing](https://github.com/BCDA-APS/use_bluesky/issues/101#issuecomment-850566810), this took about 3 minutes to resolve all the packages.  

Note The *hklpy* packaged doubled the time `conda` took to resolve all package dependencies.

**Comment by gfabbris** [comment]
Installed at 4-ID-D and tested a bit, and it looks good (I added `bluesky_widgets` and `polartools` to the 4-ID-D install). One reminder is that the diffractometer import changed from `.diffract` to `.geometry` (and `apstools.diffractometer.DiffractometerMixin` is not needed anymore).

**Comment by prjemian** [comment]
@gfabbris: I'll add *bluesky-widgets* to the list.  You'll note I separated the list into descriptive parts.

**Comment by prjemian** [comment]
Since *hklpy* is still pre-release 1.0, locations of anything can change without notice.  Still, comments such as this breaking change are worthy of direct appearance on the [release page](https://github.com/bluesky/hklpy/releases/tag/v0.3.16).  The change is noted (now) in https://github.com/bluesky/hklpy/blob/main/RELEASE_NOTES.rst and also buried in the detailed report on the wiki: https://github.com/bluesky/hklpy/wiki/release-notes-v0.3.16. 

`=--\_O_/--=`

**Pull request merged**
